CREATE TABLE Staging_Worlds_2024 (
    Player VARCHAR(250),
    Role VARCHAR(250),
    Team VARCHAR(250),
    Opponent_Team VARCHAR(250),
    Opponent_Player VARCHAR(250),
    Match_Date DATE,
    Round VARCHAR(250),
    Day VARCHAR(250),
    Patch VARCHAR(50),
    Stage VARCHAR(250),
    No_Game INT,
    All_Games INT,
    Format VARCHAR(250),
    Game_of_day VARCHAR(250),
    Side VARCHAR(50),
    Time TIME,
    Ban VARCHAR(250),
    Ban_Opponent VARCHAR(250),
    Pick VARCHAR(250),
    Pick_Opponent VARCHAR(250),
    Champion VARCHAR(250),
    Champion_Opponent VARCHAR(250),
    Outcome VARCHAR(50),
    Kills_Team INT,
    Turrets_Team INT,
    Dragon_Team INT,
    Baron_Team INT,
    Level INT,
    Kills INT,
    Deaths INT,
    Assists INT,
    KDA FLOAT,
    CS INT,
    CS_in_Teams_Jungle INT,
    CS_in_Enemy_Jungle INT,
    CSM FLOAT,
    Golds INT,
    GPM FLOAT,
    GOLD INT,
    Vision_Score INT,
    Wards_Placed INT,
    Wards_Destroyed INT,
    Control_Wards_Purchased INT,
    Detector_Wards_Placed INT,
    VSPM FLOAT,
    WPM FLOAT,
    VWPM FLOAT,
    WCPM FLOAT,
    VS INT,
    Total_damage_to_Champion INT,
    Physical_Damage INT,
    Magic_Damage INT,
    True_Damage INT,
    DPM FLOAT,
    DMG FLOAT,
    K_A_Per_Minute FLOAT,
    KP FLOAT,
    Solo_kills INT,
    Double_kills INT,
    Triple_kills INT,
    Quadra_kills INT,
    Penta_kills INT,
    GD_15 INT,
    CSD_15 INT,
    XPD_15 INT,
    LVLD_15 INT,
    Objectives_Stolen INT,
    Damage_Dealt_to_Turrets INT,
    Damage_Dealt_to_Buildings INT,
    Total_Heal INT,
    Total_Heals_On_Teammates INT,
    Damage_Self_Mitigated INT,
    Total_Damage_Shielded_On_Teammates INT,
    Time_CCing_others INT,
    Total_Time_CC_Dealt INT,
    Total_Damage_Taken INT,
    Total_Time_Spent_Dead INT,
    Consumables_Purchased INT,
    Items_Purchased INT,
    Shutdown_Bounty_collected INT,
    Shutdown_Bounty_lost INT
);
INSERT INTO Staging_Worlds_2024
SELECT
    Player,
    Role,
    Team,
    Opponent_Team,
    Opponent_Player,
    Date,
    Round,
    Day,
    Patch,
    Stage,
    No_Game,
    all_Games,
    Format,
    Game_of_day,
    Side,
    Time,
    Ban,
    Ban_Opponent,
    Pick,
    Pick_Opponent,
    Champion,
    Champion_Opponent,
    Outcome,
    Kills_Team,
    Turrets_Team,
    Dragon_Team,
    Baron_Team,
    Level,
    Kills,
    Deaths,
    Assists,
    KDA,
    CS,
    CS_in_Teams_Jungle,
    CS_in_Enemy_Jungle,
    CSM,
    Golds,
    GPM,
    GOLD,
    Vision_Score,
    Wards_placed,
    Wards_destroyed,
    Control_Wards_Purchased,
    Detector_Wards_Placed,
    VSPM,
    WPM,
    VWPM,
    WCPM,
    VS,
    Total_damage_to_Champion,
    Physical_Damage,
    Magic_Damage,
    True_Damage,
    DPM,
    DMG,
    K_A_Per_Minute,
    KP,
    Solo_kills,
    Double_kills,
    Triple_kills,
    Quadra_kills,
    Penta_kills,
    GD_15,
    CSD_15,
    XPD_15,
    LVLD_15,
    Objectives_Stolen,
    Damage_dealt_to_turrets,
    Damage_dealt_to_buildings,
    Total_heal,
    Total_Heals_On_Teammates,
    Damage_self_mitigated,
    Total_Damage_Shielded_On_Teammates,
    Time_ccing_others,
    Total_Time_CC_Dealt,
    Total_damage_taken,
    Total_Time_Spent_Dead,
    Consumables_purchased,
    Items_Purchased,
    Shutdown_bounty_collected,
    Shutdown_bounty_lost
FROM [Worlds_2024]
