CREATE TABLE Staging_Match_Stats(
	Season INT,
	Match_Date DATE,
	Event VARCHAR(250),
	Patch FLOAT,
	Blue_Team VARCHAR(250),
	Red_Team VARCHAR(250),
	Winner VARCHAR(250),
	BT_Ban_1 VARCHAR(250),
	BT_Ban_2 VARCHAR(250),
	BT_Ban_3 VARCHAR(250),
	BT_Ban_4 VARCHAR(250),
	BT_Ban_5 VARCHAR(250),
	RT_Ban_1 VARCHAR(250),
	RT_Ban_2 VARCHAR(250),
	RT_Ban_3 VARCHAR(250),
	RT_Ban_4 VARCHAR(250),
	RT_Ban_5 VARCHAR(250),
	BT_Pick_1 VARCHAR(250),
	BT_Pick_2 VARCHAR(250),
	BT_Pick_3 VARCHAR(250),
	BT_Pick_4 VARCHAR(250),
	BT_Pick_5 VARCHAR(250),
	RT_Pick_1 VARCHAR(250),
	RT_Pick_2 VARCHAR(250),
	RT_Pick_3 VARCHAR(250),
	RT_Pick_4 VARCHAR(250),
	RT_Pick_5 VARCHAR(250),
	BT_Top VARCHAR(250),
	BT_Jungle VARCHAR(250),
	BT_Mid VARCHAR(250),
	BT_ADC VARCHAR(250),
	BT_Support VARCHAR(250),
	RT_Top VARCHAR(250),
	RT_Jungle VARCHAR(250),
	RT_Mid VARCHAR(250),
	RT_ADC VARCHAR(250),
	RT_Support VARCHAR(250)
);
INSERT INTO Staging_Match_Stats
SELECT
	season,
	date,
	event,
	patch,
	blue_team,
	red_team,
	winner,
	ban_1_blue_team,
	ban_2_blue_team,
	ban_3_blue_team,
	ban_4_blue_team,
	ban_5_blue_team,
	ban_1_red_team,
	ban_2_red_team,
	ban_3_red_team,
	ban_4_red_team,
	ban_5_red_team,
	pick_1_blue_team,
	pick_2_blue_team,
	pick_3_blue_team,
	pick_4_blue_team,
	pick_5_blue_team,
	pick_1_red_team,
	pick_2_red_team,
	pick_3_red_team,
	pick_4_red_team,
	pick_5_red_team,
	top_blue_team,
	jungler_blue_team,
	mid_blue_team,
	adc_blue_team,
	support_blue_team,
	top_red_team,
	jungler_red_team,
	mid_red_team,
	adc_red_team,
	support_red_team
FROM [Match_Stats]


